### ISSUE TITLE
Upgrade link in side nav doesn't link to anything.

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/docs-app#56]
###### Copied from https://github.com/phalcon/docs/issues/1425
The Upgrade link in the side nav under General is not an anchor tag and does not link to anything.

**Comment by sergeyklay** [comment]
@niden Could you please take a look?

**Comment by diplopito** [comment]
With @ruudboon we found that the problem stems from the MD to Html conversion: the hashtag link to the anchor is being replaced by a slash, which breaks the link. In the case of https://docs.phalconphp.com/3.4/en/application-micro, in the "Method - verbs," the issue is that the links on the nav are in plural but the anchor is in singular.

**Comment by ruudboon** [comment]
Closing the issue. This is handled in one of the deployments last week.
